### PR TITLE
Remove docker in favor of manual install from dockers website

### PR DESCRIPTION
**Pull request by trevornelson**

### CODE REVIEW

**Comment by trevornelson** [comment]
@policygenius/developers 👁 

cc: @gdhagger

**Comment by trevornelson** [comment]
@gdhagger I forgot about this from Monday- is there any other specific instructions needed for docker setup, or is this all good?

**Review by j-clark — APPROVED** [review]
LGTM

**Comment by trevornelson** [comment]
Forgot about this, thanks!

**Pull request merged**
